### ISSUE TITLE
This node is really cool, I hope to improve these features~

### ISSUE THREAD

**Issue by sky958958** [erosDiffusion/ComfyUI-enricos-nodes#38]
This node is really cool~
I hope the gods can add these functions
1. The image automatically adapts to the canvas scale (now it fluctuates between large and small, some are not visible)
2. Changing the width and height will not trigger changes to the canvas, and the canvas can be fixed in proportion
3.When the canvas is not manipulated, the queue can skip this step, but now it will trigger repeatedly
I am looking forward to your work very much. Thank you~

**Comment by erosDiffusion** [comment]
hi @sky958958, thanks for your interest and ideas.

- 1: you can easily do this by adding a scale node before passing the image (for example scale image to side or scale image), but I'm planning of having a global option to set all passed images to the height of canvas (automatically) so that they are always visible. if you don't add this step images that are swapped and have different size can effectly be not usable and land outside the canvas (in some cases you can increase padding and find them again). also planning more tools to re-center the images.
- 2: not sure I get it, you would like the composition inside the node to stay withing the user-decided node size ? 
- 3: this is unfortunately a regression, I'm working on fixing it as it's really annoying to me too ;)
