### ISSUE TITLE
Hi eros only to let you know I'm working on the layer system here is a preview

### ISSUE THREAD

**Issue by kakachiex2** [erosDiffusion/ComfyUI-enricos-nodes#43]
This is TypeScript working on the UI and logic > next integration in comfyui.

https://github.com/user-attachments/assets/c8aa8ae0-e9a1-4748-93c7-7566c67ad8e1

**Comment by erosDiffusion** [comment]
if you write it without specific frameworks (vanilla js) we can try to see how to integrate it.
- in comfy ui we can a so called "dom widget" which basically is a way to say some html that provides a custom gui and one (or more) values. the "hard" part (but just because I don't know) is how to apply the clipping mask the way photoshop does (I will have to apply regardless of transforms or have a way to manipulate it iinside the canvas) next week if i find time I will make some experiments for easy parts of the widget that will some "advanced" canvas interaction (preliminary work for clipping"
-keep in mind there is a powerful extension called layer style that might already do something similar or what you want to achieve

**Comment by kakachiex2** [comment]
I'm using react typeScript with some frameworks using some frameworks I have basic knowledge in HTML, CSS and Java Script, looks like the new ComfyUI version are using TypeScript after finishing all the UI part I will furter investigate how to properly integrate it in ComfyUI and let you know.

**Comment by kakachiex2** [comment]
I'm using Cursor code editor with Claude to help me with part of the code I don't know how to implement learning a lot in the process specially dealing with Library's and addressing bugs first time in my life doing this.

**Comment by erosDiffusion** [comment]
archiving the discussion
