### ISSUE TITLE
"Compositor V3"This node is  unstable.

### ISSUE THREAD

**Issue by tanglup** [erosDiffusion/ComfyUI-enricos-nodes#59]
![image](https://github.com/user-attachments/assets/9d582156-c224-455b-9b73-255db0d21c7c)
"Compositor V3"This node is a bit unstable. If you change or add images, some image contents will become messy. You need to reconnect the node to make it work.
See the following process execution
Initial link is good
![image](https://github.com/user-attachments/assets/9b402a71-f52a-4d12-b15e-92db401c743b)
However, changing the image loading, or changing the image up and down, will cause problems with the artboard content
![image](https://github.com/user-attachments/assets/1c1f9348-9d45-47a4-9d7f-a5a151a6b002)
![image](https://github.com/user-attachments/assets/9cf2ca85-7874-4390-90af-43b106ad0315)
![image](https://github.com/user-attachments/assets/3353c3d9-c276-46da-ac32-a7024f343f84)

**Comment by erosDiffusion** [comment]
Hi @tanglup , there is a limitation with the way the "transformations" are preserved. the transforms are per slot, regardless of the content. this is meant so you could swap a similar image and find it in place. there is probably an issue with preserving width and height wich I recently indroduced 
So if swapping the connection with a differently sized image they will still be applied and cut.

If you could give the flow and the input images I can check the code. replicate and fix

**Comment by erosDiffusion** [comment]
the cutting issue should be resolved in 3.0.7 , try it out!

this was a regression as I pushed something too optimistically :)

in pr #49 transform reset toolbar is coming, it allows to restore the state transforms

in the attached workflow, for the latest version, you can see how to setup scaling so swapping works better.
[v3 resize and replace.json](https://github.com/user-attachments/files/17048335/v3.resize.and.replace.json)

keep in mind the transforms are currently preserved regardless if an input is connected or not. this is by design as of now.

**Comment by tanglup** [comment]
> @tanglup the cutting issue should be resolved in 3.0.7 , try it out!
> 
> this was a regression as I pushed something too optimistically :)
> 
> in pr #49 transform reset toolbar is coming, it allows to restore the state transforms
> 
> in the attached workflow, for the latest version, you can see how to setup scaling so swapping works better. [v3 resize and replace.json](https://github.com/user-attachments/files/17048335/v3.resize.and.replace.json)
> 
> keep in mind the transforms are currently preserved regardless if an input is connected or not. this is by design as of now.

Thanks for solving the problem.This is a  good plugin
